export const ROUTES = {
  LANDING: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  STUDENT_DASHBOARD: "/student",
  STUDENT_HACKATHONS: "/student/hackathons",
  STUDENT_REGISTRATION: "/student/registration",
  STUDENT_SUBMISSION: "/student/submission",
  STUDENT_PROFILE: "/student/profile",
  STUDENT_TEAMS: "/student/teams",
  ADMIN_DASHBOARD: "/admin",
  ADMIN_HACKATHONS: "/admin/hackathons",
  ADMIN_HACKATHON_CREATE: "/admin/hackathons/create",
  ADMIN_HACKATHON_EDIT: (slug: string) => `/admin/hackathons/${slug}/edit`,
  ADMIN_PROBLEM_STATEMENTS: "/admin/problem-statements",
  ADMIN_PROBLEM_STATEMENT_CREATE: "/admin/problem-statements/create",
  ADMIN_PROBLEM_STATEMENT_EDIT: (id: string) => `/admin/problem-statements/${id}/edit`,
  ADMIN_REGISTRATIONS: "/admin/registrations",
  ADMIN_SUBMISSIONS: "/admin/submissions",
  ADMIN_TEAMS: "/admin/teams",
  ADMIN_ANALYTICS: "/admin/analytics",
  STUDENT_HACKATHON_DETAIL: (slug: string) => `/student/hackathons/${slug}`,
  STUDENT_PROBLEM_STATEMENT_DETAIL: (slug: string, id: string) => `/student/hackathons/${slug}/problems/${id}`,
} as const;
