"""add_student_fields

Revision ID: 39b3704995a7
Revises: e59196b982a0
Create Date: 2026-06-25 22:08:05.107117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39b3704995a7'
down_revision: Union[str, None] = 'e59196b982a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('enrollment_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('branch', sa.String(), nullable=True))
    op.add_column('users', sa.Column('semester', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_enrollment_number'), 'users', ['enrollment_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_enrollment_number'), table_name='users')
    op.drop_column('users', 'semester')
    op.drop_column('users', 'branch')
    op.drop_column('users', 'enrollment_number')
    op.drop_column('users', 'team_name')
    # ### end Alembic commands ###
