"""update_hackathon_model

Revision ID: 3b7a7a202fb8
Revises: 39b3704995a7
Create Date: 2026-06-25 23:28:12.493757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b7a7a202fb8'
down_revision: Union[str, None] = '39b3704995a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create HackathonMode ENUM
    mode_enum = sa.Enum('ONLINE', 'OFFLINE', 'HYBRID', name='hackathonmode')
    mode_enum.create(op.get_bind())

    # Alter HackathonStatus ENUM
    op.execute("ALTER TABLE hackathons ALTER COLUMN status DROP DEFAULT;")
    op.execute("ALTER TYPE hackathonstatus RENAME TO hackathonstatus_old;")
    status_enum = sa.Enum('UPCOMING', 'REGISTRATION_OPEN', 'SUBMISSION_OPEN', 'CLOSED', name='hackathonstatus')
    status_enum.create(op.get_bind())
    op.execute("ALTER TABLE hackathons ALTER COLUMN status TYPE hackathonstatus USING status::text::hackathonstatus;")
    op.execute("ALTER TABLE hackathons ALTER COLUMN status SET DEFAULT 'UPCOMING';")
    op.execute("DROP TYPE hackathonstatus_old;")

    op.add_column('hackathons', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('hackathons', sa.Column('registration_start_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('hackathons', sa.Column('registration_end_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('hackathons', sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=False))
    op.add_column('hackathons', sa.Column('max_teams', sa.Integer(), nullable=True))
    op.add_column('hackathons', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.add_column('hackathons', sa.Column('banner_image', sa.String(), nullable=True))
    op.add_column('hackathons', sa.Column('location', sa.String(), nullable=False))
    op.add_column('hackathons', sa.Column('mode', sa.Enum('ONLINE', 'OFFLINE', 'HYBRID', name='hackathonmode'), nullable=False))
    op.add_column('hackathons', sa.Column('created_by', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_hackathons_slug'), 'hackathons', ['slug'], unique=True)
    op.create_foreign_key(None, 'hackathons', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_column('hackathons', 'end_date')
    op.drop_column('hackathons', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathons', sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('hackathons', sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hackathons', type_='foreignkey')
    op.drop_index(op.f('ix_hackathons_slug'), table_name='hackathons')
    op.drop_column('hackathons', 'created_by')
    op.drop_column('hackathons', 'mode')
    op.drop_column('hackathons', 'location')
    op.drop_column('hackathons', 'banner_image')
    op.drop_column('hackathons', 'is_featured')
    op.drop_column('hackathons', 'max_teams')
    op.drop_column('hackathons', 'submission_deadline')
    op.drop_column('hackathons', 'registration_end_date')
    op.drop_column('hackathons', 'registration_start_date')
    op.drop_column('hackathons', 'slug')
    # ### end Alembic commands ###
