"""Add problem_statement model

Revision ID: 51366b224a0a
Revises: 3b7a7a202fb8
Create Date: 2026-06-25 23:53:21.742457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51366b224a0a'
down_revision: Union[str, None] = '3b7a7a202fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_statements', sa.Column('problem_code', sa.String(), nullable=False))
    from sqlalchemy.dialects import postgresql
    difficulty_enum = postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='problemdifficulty')
    difficulty_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('problem_statements', sa.Column('difficulty', difficulty_enum, nullable=False))
    op.add_column('problem_statements', sa.Column('category', sa.String(), nullable=False))
    op.add_column('problem_statements', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_problem_statements_category'), 'problem_statements', ['category'], unique=False)
    op.create_index(op.f('ix_problem_statements_problem_code'), 'problem_statements', ['problem_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_statements_problem_code'), table_name='problem_statements')
    op.drop_index(op.f('ix_problem_statements_category'), table_name='problem_statements')
    op.drop_column('problem_statements', 'is_published')
    op.drop_column('problem_statements', 'category')
    op.drop_column('problem_statements', 'difficulty')
    op.drop_column('problem_statements', 'problem_code')
    
    from sqlalchemy.dialects import postgresql
    difficulty_enum = postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='problemdifficulty')
    difficulty_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
