"""Refactor registration and submission modules

Revision ID: 5bbf14c3624c
Revises: 51366b224a0a
Create Date: 2026-06-26 10:41:58.699111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bbf14c3624c'
down_revision: Union[str, None] = '51366b224a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("COMMIT")
    op.execute("ALTER TYPE registrationstatus ADD VALUE IF NOT EXISTS 'UNDER_REVIEW'")
    op.execute("ALTER TYPE registrationstatus ADD VALUE IF NOT EXISTS 'WITHDRAWN'")
    op.execute("ALTER TYPE submissionstatus ADD VALUE IF NOT EXISTS 'UNDER_REVIEW'")
    op.execute("ALTER TYPE submissionstatus ADD VALUE IF NOT EXISTS 'ACCEPTED'")
    op.execute("ALTER TYPE submissionstatus ADD VALUE IF NOT EXISTS 'REJECTED'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('leader_id', sa.Uuid(), nullable=True))
    op.add_column('registrations', sa.Column('team_id', sa.Uuid(), nullable=True))
    op.add_column('registrations', sa.Column('problem_statement_id', sa.Uuid(), nullable=True))
    op.add_column('registrations', sa.Column('admin_remarks', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('approved_by', sa.Uuid(), nullable=True))
    op.add_column('registrations', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'registrations', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'registrations', 'users', ['leader_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'registrations', 'problem_statements', ['problem_statement_id'], ['id'], ondelete='SET NULL')
    op.add_column('submissions', sa.Column('demo_video_url', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('ppt_url', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('zip_url', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('project_description', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('tech_stack', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('submissions', sa.Column('feedback', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('remarks', sa.Text(), nullable=True))
    op.drop_column('submissions', 'presentation_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('presentation_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('submissions', 'remarks')
    op.drop_column('submissions', 'feedback')
    op.drop_column('submissions', 'score')
    op.drop_column('submissions', 'notes')
    op.drop_column('submissions', 'tech_stack')
    op.drop_column('submissions', 'project_description')
    op.drop_column('submissions', 'zip_url')
    op.drop_column('submissions', 'ppt_url')
    op.drop_column('submissions', 'demo_video_url')
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_column('registrations', 'approved_at')
    op.drop_column('registrations', 'approved_by')
    op.drop_column('registrations', 'admin_remarks')
    op.drop_column('registrations', 'problem_statement_id')
    op.drop_column('registrations', 'team_id')
    op.drop_column('registrations', 'leader_id')
    # ### end Alembic commands ###
