"""team_v2_migration

Revision ID: d05749aac44a
Revises: 32f162fafecf
Create Date: 2026-06-26 23:04:56.103737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05749aac44a'
down_revision: Union[str, None] = '32f162fafecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('hackathon_id', sa.Uuid(), nullable=True))
    op.add_column('teams', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('banner_url', sa.String(), nullable=True))
    op.create_foreign_key(None, 'teams', 'hackathons', ['hackathon_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
    
    # Data Migration: Link teams to hackathons based on registrations
    conn = op.get_bind()
    conn.execute(sa.text('''
        UPDATE teams 
        SET hackathon_id = r.hackathon_id 
        FROM registrations r 
        WHERE r.team_id = teams.id
    '''))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'banner_url')
    op.drop_column('teams', 'logo_url')
    op.drop_column('teams', 'hackathon_id')
    # ### end Alembic commands ###
